export const Images = {
  email: require("./email.svg"),
  logo: require("./logo.svg"),
  slide1: require("./slide1.png"),
  slide2: require("./slide2.png"),
  slide3: require("./slide3.png"),
  sublogo: require("./sublogo.svg"),
  lock: require("./lock.svg"),
  password: require("./lock.svg"),
  facebookicon: require("./facebook.png"),
  google: require("./google.png"),
  fullname: require("./fullname.svg"),
  homeIocn: require("./home.svg"),
  notification: require("./notificaitons.svg"),
  favourite: require("./favourite.svg"),
  chat: require("./chat.svg"),
  booknow: require("./booknow.svg"),
  filtericon: require("./filtericon.svg"),
  car: require("./car.svg"),
  location: require("./location.svg"),
  wifi: require("./wifi.svg"),
};
